name: TownyBagEconomy
main: land.jarochitoland.townybankbridge.TownyBankBridgePlugin
version: 1.0.0-JL.4
api-version: '1.21'
author: Jarochitoland
softdepend: [Towny, Citizens, BagOfGold]

commands:
  tbe:
    description: TownyBagEconomy admin and mayor commands
    usage: /tbe <npc|sync|reload>
    aliases: [townybageconomy]

permissions:
  townybageconomy.admin:
    default: op
  townybageconomy.npc.move:
    default: true
